### PR TITLE
Visual Studio 2022 Support

### PR DESCRIPTION
**Pull request by CursedSheep**
Updated the version of the dependencies and fixed the manifest settings for it to work on visual studio 2022.

### CODE REVIEW

**Comment by 1thenikita** [comment]
I will make some edits and do a transfer, thank you.

**Comment by d347h-n3k0** [comment]
About when will the transfer be pushed to the main or some "beta" release for the preview? Don't want to presure you just asking so i don't miss it

**Comment by 1thenikita** [comment]
> About when will the transfer be pushed to the main or some "beta" release for the preview? Don't want to presure you just asking so i don't miss it

Hi. It's okay that you asked the question. I am currently preparing for the championship and because of this I am temporarily not engaged in the expansion. I will accept this update later, I just want to add new features along with it.

**Comment by d347h-n3k0** [comment]
Sounds great! God luck!

**Comment by CursedSheep** [comment]
> Sounds great! God luck!

Use my fork if you want to flex what you're coding right away ;)

**Comment by Zenixas** [comment]
Thank you CursedSheep, very cool!

**Pull request merged**
